web-hospital/HospitalMS/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using HospitalMS.Models;


namespace HospitalMS.Controllers
{
    public class AccountsController : Controller
    {
        

        // GET: Accounts
        [HttpGet]
        public ActionResult Login()
        {
            
            return View();
        }

        [HttpGet]
        public ActionResult Signup()
        {
            
            return View();
        }
      

        [HttpPost]
        public ActionResult Login(LoginView model)
        {
            if (ModelState.IsValid)
            {
                using (var dc = new HospitalDBContextEntities())
                {
                    var user = dc.Patients.FirstOrDefault(u => u.Email == model.Email);

                    if (user != null && user.Password == Crypto.Hash(model.Password))
                    {
                        FormsAuthentication.SetAuthCookie(model.Email, false); 
                        return RedirectToAction("Index", "Home"); 
                    }
                    else
                    {
                        ModelState.AddModelError("", "Invalid e-mail or password.");
                    }
                }
            }

            
            return View(model);
        }





        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Signup([Bind(Exclude = "IsEmailVerified,ActivationCode")] Patients user)
        {
            bool Status = false;
            string message = "";

            
            if (ModelState.IsValid)
            {
                #region //Email is already exist
                var isExist = IsEmailExist(user.Email);
                if (isExist)
                {
                    ModelState.AddModelError("EmailExist", "Email already exists");
                    return View(user);
                }
                #endregion

                
                user.Password = Crypto.Hash(user.Password);
                user.ConfirmPassword = Crypto.Hash(user.ConfirmPassword);

                user.IsEmailVerified1 = false;

                #region //Save Data to DB
                using (HospitalDBContextEntities dc = new HospitalDBContextEntities())
                {
                    dc.Patients.Add(user);
                    dc.SaveChanges();

                    // No email verification and activation code sent
                    message = "Registration successfully done.";
                    Status = true;
                }
                #endregion
            }
            else
            {
                message = "Invalid Request";
            }

            ViewBag.Message = message;
            ViewBag.Status = Status;

            return View();
        }


        [NonAction]
        public bool IsEmailExist(string emailID)
        {
            using (HospitalDBContextEntities dc = new HospitalDBContextEntities()) 
            {
                var x = dc.Patients.Where(a => a.Email == emailID).FirstOrDefault();
                return x != null;
            }
        }


        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }


    }

   
}

web-hospital/HospitalMS/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using HospitalMS.Models;

namespace HospitalMS.Controllers
{
    public class DoctorsController : Controller
    {
        [HttpGet]
        public ActionResult DoctorLogin()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DoctorLogin(DoctorLogin model)
        {
            if (ModelState.IsValid)
            {
                using (var dc = new HospitalDBContextEntities())
                {
                    var user = dc.Doctors1.FirstOrDefault(u => u.Email == model.Email);

                    if (user != null)
                    {
                        FormsAuthentication.SetAuthCookie(model.Email, false);

                        
                        return RedirectToAction("Index", "Prescription");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Invalid e-mail or password.");
                    }
                }
            }

            
            return View(model);
        }
    }
}

web-hospital/HospitalMS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HospitalMS.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        
        public ActionResult AboutUs()
        {
            return View();
        }

        
        public ActionResult ContactUs()
        {
            return View();
        }

        public ActionResult Doctors1()
        {
            return View();
        }

        public ActionResult Gallery1()
        {
            return View();
        }

        public ActionResult MedicalUnits1()
        {
            return View();
        }
    }
}

web-hospital/HospitalMS/Views/Home/AboutUs.cshtml
@{
    ViewBag.Title = "AboutUs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="home">
    <img src="~/images/about.jpg" alt="Home Image">
</section>

<section id="services">
    <div id="slider">
        <div class="slider-container">
            <img src="~/images/aboutfoto1.jpg" alt="Resim 1">
            <img src="~/images/aboutfoto2.jpg" alt="Resim 2">
        </div>
    </div>

    <div class="aboutustext">
        <h2>About Us</h2>
        <h3>Lifespring Hospital:</h3>
        <p>
            Lifespring Hospital is one of the leading institutions in the healthcare sector of Istanbul. Our
            modern facility reflects our commitment to providing comprehensive and high-quality healthcare
            services to our patients.
        </p>
        <br>
        <h3>Service Areas:</h3>

        <p>
            Lifespring Hospital responds to a variety of healthcare needs, ranging from emergency interventions
            to surgical operations, by offering a broad range of services. Our intensive care units, equipped
            with state-of-the-art technology, provide the highest level of care to critically ill patients.
            Additionally, through our outpatient clinics, we offer a wide range of services, from routine health
            check-ups to specialized examinations.
        </p>
        <br>
        <h3>Doctors and Staff:</h3>

        <p>
            At Lifespring Hospital, our specialized doctors, experienced nurses, and support staff work together
            to provide patients with an individualized and attentive approach to healthcare. Based on a strong
            ethical values system, we have formed a team focused on the health of our patients.
        </p>
        <br>
        <h3>Community Services and Education:</h3>

        <p>
            As a hospital, Lifespring Hospital not only focuses on treatment but also aims to contribute to
            community health. We organize health awareness activities, seminars, and educational programs for
            our local communities to contribute to the development of public health.
        </p>
        <p>
            Lifespring Hospital is a healthcare institution known for its quality healthcare services,
            technological infrastructure, and emphasis on patient satisfaction. We invite you to meet our expert
            team and explore our modern facility.
        </p>
    </div>
</section>

web-hospital/HospitalMS/Views/Home/ContactUs.cshtml
@{
    ViewBag.Title = "ContactUs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="home">
    <img src="~/images/contact.jpg" alt="Home Image">
</section>

<section id="services2">
    <h2>Contact Us</h2>
    <p>We are listening to you..</p>
    <p>Dear visitor; You can share your opinions, suggestions, complaints and thanks with us.</p>
    <p>Phone: (000) 111-1111</p>
    <p>Fax : (000) 111-1111</p>
    <p>Github: https://github.com/MustafaKaragz </p>
    
</section>

<div class="map-container">
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d1449.914603546563!2d29.027284904966177!3d40.99043606183929!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1str!2str!4v1699990073161!5m2!1str!2str" width="1000" height="450" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</div>

web-hospital/HospitalMS/Views/Home/Doctors1.cshtml
@{ ViewBag.Title = "Doctors1"; }





<div class="search-bardoc">
    <select id="department-filter" onchange="filterByDepartment()">
        <option value="all">All Chapters</option>
        <option value="Pediatrics">Pediatrics</option>
        <option value="Neurology">Neurology</option>
        <option value="Hematology">Hematology</option>
        <option value="Urology">Urology</option>
        <option value="Dermatology">Dermatology</option>
        <option value="Cardiology">Cardiology</option>


    </select>
</div>


<section id="doctor-grid" class="doctor-grid">

    <div class="doctor-card">
        <img src="~/images/1doctor.jpg" alt="Doktorun Resmi">
        <div class="doctor-info">
            <h3>
                Prof. Dr.Naci İbrahim Çelik<h3>
                    <p>Pediatrics</p>
        </div>
    </div>
    <div class="doctor-card">
        <img src="~/images/2doctor.jpg" alt="Doktorun Resmi">
        <div class="doctor-info">
            <h3>
                Prof. Dr. Melih Kasımoğlu<h3>
                    <p>Dermatology</p>
        </div>
    </div><div class="doctor-card">
        <img src="~/images/3doctor.jpg" alt="Doktorun Resmi">
        <div class="doctor-info">
            <h3>
                Op.Dr.Hakan Gündoğan<h3>
                    <p>Neurology</p>
        </div>
    </div>
    <div class="doctor-card">
        <img src="~/images/4doctor.jpg" alt="Doktorun Resmi">
        <div class="doctor-info">
            <h3>
                Prof. Dr.Güncel Öztürk<h3>
                    <p>Orthopedics</p>
        </div>
    </div>
    <div class="doctor-card">
        <img src="~/images/5doctor.jpg" alt="Doktorun Resmi">
        <div class="doctor-info">
            <h3>
                Dr. Arzu Keskin Dalkıran<h3>
                    <p>Neurology</p>
        </div>
    </div><div class="doctor-card">
        <img src="~/images/6doctor.jpg" alt="Doktorun Resmi">
        <div class="doctor-info">
            <h3>
                Prof.Dr.Mustafa ŞENER<h3>
                    <p>Hematology</p>
        </div>
    </div>
    <div class="doctor-card">
        <img src="~/images/7doctor.jpg" alt="Doktorun Resmi">
        <div class="doctor-info">
            <h3>
                Op.Dr.Neslihan ŞENOCAK<h3>
                    <p>Hematology</p>
        </div>
    </div>
    <div class="doctor-card">
        <img src="~/images/8doctor.jpg" alt="Doktorun Resmi">
        <div class="doctor-info">
            <h3>
                Prof. Dr. David Ruacan<h3>
                    <p>Hematology</p>
        </div>
    </div><div class="doctor-card">
        <img src="~/images/9doctor.jpg" alt="Doktorun Resmi">
        <div class="doctor-info">
            <h3>
                Prof. Dr. Alev Işık Kılıç<h3>
                    <p>Urology</p>
        </div>
    </div>
    <div class="doctor-card">
        <img src="~/images/10doctor.jpg" alt="Doktorun Resmi">
        <div class="doctor-info">
            <h3>
                Dr.Münevver Güllüoğlu<h3>
                    <p>Urology</p>
        </div>
    </div>
    <div class="doctor-card">
        <img src="~/images/11doctor.jpg" alt="Doktorun Resmi">
        <div class="doctor-info">
            <h3>
                Prof. Dr. Okan Baş<h3>
                    <p>Dermatology</p>
        </div>
    </div><div class="doctor-card">
        <img src="~/images/12doctor.jpg" alt="Doktorun Resmi">
        <div class="doctor-info">
            <h3>
                Dr. Melek Kabak<h3>
                    <br>  <p>Dermatology</p>
        </div>
    </div>
    <div class="doctor-card">
        <img src="~/images/13doctor.jpg" alt="Doktorun Resmi">
        <div class="doctor-info">
            <h3>
                Prof. Dr. Doğuş Kıran<h3>
                    <p>Urology</p>
        </div>
    </div>
    <div class="doctor-card">
        <img src="~/images/14doctor.jpg" alt="Doktorun Resmi">
        <div class="doctor-info">
            <h3>
                Prof. Dr. Hüseyin Dal<h3>
                    <p>Cardiology</p>
        </div>
    </div><div class="doctor-card">
        <img src="~/images/15doctor.jpg" alt="Doktorun Resmi">
        <div class="doctor-info">
            <h3>
                Prof. Dr.İbrahim Usta<h3>
                    <p>Cardiology</p>
        </div>
    </div>

    </div>


</section>

web-hospital/HospitalMS/Views/Home/Gallery1.cshtml
@{ ViewBag.Title = "Gallery1"; }




<div class="gallery-container">

    <div class="gallery">
        <img src="~/images/1hospital.jpg" alt="Doktorun Resmi">
    </div>
    <div class="gallery">
        <img src="~/images/2hospital.jpg" alt="Doktorun Resmi">
    </div>
    <div class="gallery">
        <img src="~/images/3hospital.jpg" alt="Doktorun Resmi">
    </div>
    <div class="gallery">
        <img src="~/images/4hospital.jpg" alt="Doktorun Resmi">
    </div>
    <div class="gallery">
        <img src="~/images/5hospital.jpg" alt="Doktorun Resmi">
    </div>
    <div class="gallery">
        <img src="~/images/6hospital.jpg" alt="Doktorun Resmi">
    </div>
    <div class="gallery">
        <img src="~/images/7hospital.jpg" alt="Doktorun Resmi">
    </div>
    <div class="gallery">
        <img src="~/images/8hospital.jpg" alt="Doktorun Resmi">
    </div>
    <div class="gallery">
        <img src="~/images/9hospital.jpg" alt="Doktorun Resmi">
    </div>
    <div class="gallery">
        <img src="~/images/10hospital.jpg" alt="Doktorun Resmi">
    </div>
    <div class="gallery">
        <img src="~/images/11hospital.jpg" alt="Doktorun Resmi">
    </div>
    <div class="gallery">
        <img src="~/images/12hospital.jpg" alt="Doktorun Resmi">
    </div>

</div>

web-hospital/HospitalMS/Views/Home/Index.cshtml
@{ ViewBag.Title = "Index";
                Layout = "~/Views/Shared/_Layout.cshtml"; }

<section id="home">
    <img src="~/images/mainfoto.jpg" alt="Home Image">

</section>





<div class="carousel1">
    <img src="~/images/carosel1.jpg" class="active1">
    <img src="~/images/carosel2.jpg">
    <img src="~/images/carosel3.jpg">
    <div class="next1"><i class="fa-solid fa-arrow-right fa-2xl" style="color: rgb(0, 0, 0);"></i></div>
    <div class="prev1"><i class="fa-solid fa-arrow-left fa-2xl" style="color: rgb(0, 0, 0);"></i></div>
</div>



<div class="grid-container1">
    <div class="grid-item1" onclick="redirectToLogin1();">
        <div class="icon1"><i class="fa-solid fa-user-doctor" style="color: #ffffff;"></i></div>
        Doktor
    </div>
    <div class="grid-item1" onclick="redirectToLogin();">
        <div class="icon1">&#128657;</div>
        HASTA
    </div>
</div>


<section id="services1">
    <div class="icon-container1">
        <img src="~/images/hearticon.png" alt="General Healthcare" class="hospital-icon1">
        <img src="~/images/pillicon.png" alt="Pharmacy" class="hospital-icon1">
        <img src="~/images/plastericon.png" alt="Cardiology" class="hospital-icon1">
        <img src="~/images/stethoscopeicon.png" alt="First Aid" class="hospital-icon1">
    </div>

    <div class="cards-container1">
        <div class="card1">
            <img src="~/images/card1.jpg" alt="Healthcare Professionals" class="card-image1">
            <div class="card-content1">
                <h3><b>Your Health is Our Priority</b></h3>
                <p class="summary1"><i><br>Our Only Priority is You</i></p>
                <p class="full-message1">
                    We, Lifespring Hospital, take pride in providing you with high-quality and reliable
                    healthcare services. With our experienced team of doctors and state-of-the-art medical
                    equipment, we are here to
                    deliver the best possible treatment to our patients.<br> <br>
                </p>
                <button class="detail-button1">More Information</button>
            </div>
        </div>
        <div class="card1">
            <img src="~/images/card2.jpg" alt="Healthcare Professionals" class="card-image1">
            <div class="card-content1">
                <h3><b>Our Doctors</b></h3>
                <p class="summary1"><i><br> All of our doctors are experts in their field. <br> <br> </i></p>
                <p class="full-message1">
                    Our expert doctors, specializing in their respective fields, serve in
                    our hospital with constantly updated knowledge and skills. Our top-notch doctors, focusing
                    on your health, create personalized treatment plans for each patient, offering the most
                    effective solutions to health issues.<br> <br> 
                </p>
                <button class="detail-button1">More Information</button>
            </div>
        </div>

        <div class="card1">
            <img src="~/images/card3.jpg" alt="Healthcare Professionals" class="card-image1">
            <div class="card-content1">
                <h3><b>Our Services</b></h3>
                <p class="summary1"><i> <br> Our best services for you <br> <br></i></p>
                <p class="full-message1">
                    General Health Check-ups<br> Emergency Services <br>Surgical Interventions
                    <br> Cardiology and Heart Health <br> Orthopedics <br> Neurology
                    <br>Dermatology <br>Urology <br>Hematology <br>Pediatrics <br> <br>
                </p>
                <button class="detail-button1">More Information</button>
            </div>
        </div>


        <div class="card1">
            <img src="~/images/card4.jpg" alt="Healthcare Professionals" class="card-image1">
            <div class="card-content1">
                <h3><b>Why Choose Us?</b></h3>
                <p class="summary1"><i> <br> Patient And Respect Are The Priority.</i></p>
                <p class="full-message1">
                    We not only provide medical services to our patients but also make the treatment process more meaningful by emphasizing respect, transparency, and patient satisfaction.
                    If you are looking for reliable and effective solutions for your health, Lifespring Hospital is here for you.
                </p>
                <button class="detail-button1">More Information</button>
            </div>
        </div>

    </div>
</section>

<script>
    function redirectToLogin() {
        window.location.href = '@Url.Action("Login", "Accounts")';
    }
</script>

<script>
    function redirectToLogin1() {
        window.location.href = '@Url.Action("DoctorLogin", "Doctors")';
    }
</script>

web-hospital/HospitalMS/Views/Home/MedicalUnits1.cshtml
@{ ViewBag.Title = "MedicalUnits1";
                Layout = "~/Views/Shared/_Layout.cshtml"; }


<div class="medicalbody">
    <div id="main-contentmedical">

        <div id="medical-units-heading">Medical Units</div>

        <ul id="medical-units-list">
            <li class="medical-unit">
                <h3>Cardiology Department</h3>
                <img src="~/images/cardiology.jpg" alt="Cardiology Department">
                <p>Experienced cardiologists providing high-quality care for heart health.</p>
            </li>

            <li class="medical-unit">
                <h3>Orthopedics Department</h3>
                <img src="~/images/orthopedics.jpg" alt="Orthopedics Department">
                <p>Specialized in orthopedic and traumatology services to enhance musculoskeletal health.</p>
            </li>

            <li class="medical-unit">
                <h3>Neurology Department</h3>
                <img src="~/images/neurology.jpg" alt="Neurology Department">
                <p>Experts in the diagnosis and treatment of disorders affecting the nervous system.</p>
            </li>

            <li class="medical-unit">
                <h3>Dermatology Department</h3>
                <img src="~/images/dermatology.jpg" alt="Dermatology Department">
                <p>Specializing in skin-related conditions and cosmetic dermatology services.</p>
            </li>

            <li class="medical-unit">
                <h3>Urology Department</h3>
                <img src="~/images/urology.jpg" alt="Urology Department">
                <p>
                    Specialized in urological services, including the diagnosis and treatment of conditions related
                    to the urinary tract.
                </p>
            </li>



            <li class="medical-unit">
                <h3>Hematology</h3>
                <img src="~/images/emotology.jpg" alt="Emotology">
                <p>Hematology is the branch of science that deals with blood diseases as well as diseases of blood-forming organs such as spleen and bone marrow.</p>
            </li>

            <li class="medical-unit">
                <h3>Pediatrics</h3>
                <img src="~/images/pediatri.jpg" alt="Child">
                <p>Child health and diseases, also known as pediatrics, deals with individuals from birth to adolescence.</p>
            </li>



        </ul>
    </div>

</div>